create database medic_guide;
use medic_guide;
CREATE TABLE `dim_usuario` (
  `SK_USUARIO` int NOT NULL AUTO_INCREMENT,
  `NM_USUARIO` varchar(450) DEFAULT NULL,
  `EMAIL_USUARIO` varchar(450) DEFAULT NULL,
  `DS_USUARIO` varchar(45) DEFAULT NULL,
  `SENHA_USUARIO` varchar(450) DEFAULT NULL,
  `CIDADE` varchar(450) DEFAULT NULL,
  `CEP_ID` varchar(45) DEFAULT NULL,
  `CEP` varchar(450) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `D_E_L_E_T` char(1) DEFAULT NULL,
  PRIMARY KEY (`SK_USUARIO`)
);
CREATE TABLE `dim_rota` (
  `SK_ROTA` int NOT NULL AUTO_INCREMENT,
  `DS_ROTA` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SK_ROTA`)
);
CREATE TABLE `dim_metodo` (
  `SK_METODO` int NOT NULL AUTO_INCREMENT,
  `DS_METODO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SK_METODO`)
);
CREATE TABLE `dim_privilegio` (
  `SK_PRIVILEGIO` int NOT NULL AUTO_INCREMENT,
  `DS_PRIVILEGIO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SK_PRIVILEGIO`)
);
CREATE TABLE `dim_funcionalidade` (
  `SK_FUNCIONALIDADE` int NOT NULL AUTO_INCREMENT,
  `DS_FUNCIONALIDADE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SK_FUNCIONALIDADE`)
); 
CREATE TABLE `dim_politica` (
  `SK_POLITICA` int NOT NULL AUTO_INCREMENT,
  `SK_ROTA` int DEFAULT NULL,
  `SK_METODO` int DEFAULT NULL,
  `SK_FUNCIONALIDADE` int DEFAULT NULL,
  `SK_PRIVILEGIO` int DEFAULT NULL,
  `DS_POLITICA` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SK_POLITICA`),
  KEY `DIM_POLITICA_X_DIM_ROTA_idx` (`SK_ROTA`),
  KEY `DIM_POLITICA_X_DIM_METODO_idx` (`SK_METODO`),
  KEY `DIM_POLITICA_X_DIM_FUNCIONALIDADE_idx` (`SK_FUNCIONALIDADE`),
  KEY `DIM_POLITICA_X_DIM_PRIVILEGIO_idx` (`SK_PRIVILEGIO`),
  CONSTRAINT `DIM_POLITICA_X_DIM_FUNCIONALIDADE` FOREIGN KEY (`SK_FUNCIONALIDADE`) REFERENCES `dim_funcionalidade` (`SK_FUNCIONALIDADE`),
  CONSTRAINT `DIM_POLITICA_X_DIM_METODO` FOREIGN KEY (`SK_METODO`) REFERENCES `dim_metodo` (`SK_METODO`),
  CONSTRAINT `DIM_POLITICA_X_DIM_PRIVILEGIO` FOREIGN KEY (`SK_PRIVILEGIO`) REFERENCES `dim_privilegio` (`SK_PRIVILEGIO`),
  CONSTRAINT `DIM_POLITICA_X_DIM_ROTA` FOREIGN KEY (`SK_ROTA`) REFERENCES `dim_rota` (`SK_ROTA`)
);
CREATE TABLE `fat_atribuicao` (
  `SK_ATRIBUICAO` int NOT NULL AUTO_INCREMENT,
  `SK_USUARIO` int DEFAULT NULL,
  `SK_POLITICA` int DEFAULT NULL,
  PRIMARY KEY (`SK_ATRIBUICAO`),
  KEY `FAT_ATRIBUICAO_X_DIM_USUARIO_idx` (`SK_USUARIO`),
  KEY `FAT_ATRIBUICAO_X_DIM_POLITICA_idx` (`SK_POLITICA`),
  CONSTRAINT `FAT_ATRIBUICAO_X_DIM_POLITICA` FOREIGN KEY (`SK_POLITICA`) REFERENCES `dim_politica` (`SK_POLITICA`),
  CONSTRAINT `FAT_ATRIBUICAO_X_DIM_USUARIO` FOREIGN KEY (`SK_USUARIO`) REFERENCES `dim_usuario` (`SK_USUARIO`)
);
CREATE TABLE `pacientes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(450) DEFAULT NULL,
  `age` int DEFAULT NULL,
  `sex` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `medic_guide`.`dim_usuario` (`NM_USUARIO`, `EMAIL_USUARIO`, `DS_USUARIO`, `SENHA_USUARIO`) VALUES ('Root Medic Guide', 'root@gmail.com', 'root', '$2b$10$jCCgOqe1Decmgg5VGUKYruQW7KQpGK4rQA6QbRz2aK2N8wjiYc06W');
INSERT INTO `medic_guide`.`dim_rota` (`DS_ROTA`) VALUES ('/user');
INSERT INTO `medic_guide`.`dim_funcionalidade` (`DS_FUNCIONALIDADE`) VALUES ('CRIAR USUARIO');
INSERT INTO `medic_guide`.`dim_metodo` (`DS_METODO`) VALUES ('PUT');
INSERT INTO `medic_guide`.`dim_privilegio` (`DS_PRIVILEGIO`) VALUES ('CRIAR USUARIO');
INSERT INTO `medic_guide`.`dim_politica` (`SK_ROTA`, `SK_METODO`, `SK_FUNCIONALIDADE`, `SK_PRIVILEGIO`, `DS_POLITICA`) VALUES ('1', '1', '1', '1', 'CRIAR USUARIO');INSERT INTO `medic_guide`.`fat_atribuicao` (`SK_USUARIO`, `SK_POLITICA`) VALUES ('1', '1');


